name: Bank-App Docker Container

on: 
   push:
  #pull_requests:
     branches: dev
   
jobs:
   Build_docker:
     runs-on: ubuntu-latest
   
     steps:
     - uses: actions/checkout@v3
     - name: package docker image
       run: |
        sudo apt update
        echo build Devops class Docker Container
        docker build . --file Dockerfile --tag bank-app:v1
